### ISSUE TITLE
[Question]How to build wit lineageOS 16

### ISSUE THREAD

**Issue by HeZaiJin** [Magendanz/android_device_samsung_gta3xlwifi#1]
Hi Man,

I am trying to compile the complete source code with lineageOS 16.0. However there are always compilation problems happended. Is there any guide I can learn from? Looking forward to your generous reply.

`
jidou@jidou-System-Product-Name:~/workspace/lineage$ brunch omni_gta3xlwifi-userdebug
including vendor/lineage/vendorsetup.sh
Trying dependencies-only mode on a non-existing device tree?

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20200421-UNOFFICIAL-
TARGET_PRODUCT=omni_gta3xlwifi
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-96-generic-x86_64-Ubuntu-16.04.5-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=/home/jidou/workspace/lineage/out
RECOVERY_VARIANT=twrp
============================================
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20200421-UNOFFICIAL-
TARGET_PRODUCT=omni_gta3xlwifi
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-96-generic-x86_64-Ubuntu-16.04.5-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=/home/jidou/workspace/lineage/out
RECOVERY_VARIANT=twrp
============================================
ninja: no work to do.
ninja: no work to do.
No need to regenerate ninja file
No need to regenerate ninja file
[100% 1/1] build bacon
FAILED: bacon 
/bin/bash -c "(ln -f  /home/jidou/workspace/lineage/out/target/product/gta3xlwifi/lineage-16.0-20200421-UNOFFICIAL-.zip ) && (md5sum /home/jidou/workspace/lineage/out/target/product/gta3xlwifi/lineage-16.0-20200421-UNOFFICIAL-.zip | sed \"s|/home/jidou/workspace/lineage/out/target/product/gta3xlwifi/||\" > /home/jidou/workspace/lineage/out/target/product/gta3xlwifi/lineage-16.0-20200421-UNOFFICIAL-.zip.md5sum ) && (echo \"Package Complete: /home/jidou/workspace/lineage/out/target/product/gta3xlwifi/lineage-16.0-20200421-UNOFFICIAL-.zip\" >&2 )"
ln: failed to access '/home/jidou/workspace/lineage/out/target/product/gta3xlwifi/lineage-16.0-20200421-UNOFFICIAL-.zip': \u6ca1\u6709\u90a3\u4e2a\u6587\u4ef6\u6216\u76ee\u5f55
ninja: build stopped: subcommand failed.
11:52:32 ninja failed with: exit status 1

#### failed to build some targets (26 seconds) ####
`

**Comment by Magendanz** [comment]
This is not an issue with my TWRP device tree.  I appreciate that you want help with building LineageOS, but spamming my GitHub repos isn't the way to get it.
